### PR TITLE
Svelte: support bind:value

### PR DESCRIPTION
**Pull request by SkaterDad**
Firstly, thanks for this library!  `yjs` had me interested, but you've made it so much simpler to use.

The combination of SyncedStore and the WebRTC & IndexedDb providers blew me away.  Collaborative, offline-capable data in less than 5 minutes of work? 
# 🤯 

## Description

This PR adds support for Svelte's `bind:value` syntax.  The Svelte compiler expects there to be a `set` method on the store.
```js
	function input_input_handler(each_value, item_index) {
		each_value[item_index].title = this.value;
		theStore.set($theStore);
	}
```

Since we're editing the underlying reactive objects directly, the `set` method can just be a simple `() => {}` stub.

## Example
Same code, but with the types removed.
https://codesandbox.io/s/svelte-syncedstore-example-lb1g7?file=/App.svelte

### CODE REVIEW

**Comment by YousefED** [comment]
Great, thanks @SkaterDad and glad to hear about your experience :)!

Would you be interested in helping out by adding a Svelte example to https://syncedstore.org/docs/? (similar to the React / Vue examples?). This would definitely be useful and maybe we can then share it in the Svelte community to get more people excited

**Comment by YousefED** [comment]
> Yes, I should be able to help with that. Same Todo app?

Yes I think that would be cool! I think most work would be getting the live example (using sandpack) to work. Most of this code is in https://github.com/YousefED/SyncedStore/tree/main/docs/src/theme/CodeBlock. Let me know if you need help to figure this out! (I'm also available on Discord)

The latest version of Sandpack (the live code editor) has a Svelte theme (they just added that), so that should be helpful:

https://github.com/codesandbox/sandpack/blob/2d0c85c5ef4fa856c83e539e2c9e2ffd804fa366/sandpack-react/src/templates/svelte.ts.



> I'm hoping to do more experimentation with complex data, as well. Is this library able to handle nested object updates (trees)? I read it's possible with yjs, but you'd have to define each nested object as a y map?

Yes, this is definitely possible with Yjs. Yjs provides data structures such as Y.Map and Y.Array for this. However, SyncedStore was designed exactly to make this easier; so with SyncedStore you can pass any JSON structure, and it maintains underlying Y.Map (for objects) and Y.Array (for arrays) automatically.

**Comment by SkaterDad** [comment]
Hi, would you be able to push an updated package to npm for use in the examples?

I spent some time working on the sandpack examples but kept running into strange errors.  Was going to give it another try this weekend, though.

**Comment by YousefED** [comment]
Done! Svelte package has been updated: https://www.npmjs.com/package/@syncedstore/svelte

**Comment by SkaterDad** [comment]
Thanks!   Feels like Codesandbox isn't playing well with Svelte.  Running into an error just like this one: https://github.com/EmilTholin/svelte-routing/issues/92

The code is all fine, but it doesn't work unless you open the Codesandbox and reinstall the Svelte dependency.  Super weird and not a great user experience. 

For now I'll just make a PR with some example code, and maybe a Svelte REPL.

**Pull request merged**
